language: ruby
cache: bundler

os:
  - linux

rvm:
  - jruby
  - 1.9.2
  - 1.9.3
  - 2.5.5
  - 2.6.3

jobs:
  include:
    - os: osx
      osx_image: xcode7.3
      rvm: 1.9.3
    - os: osx
      rvm: 2.5.5
    - os: osx
      rvm: 2.6.3
    - stage: deploy
      if: branch = master
      os: linux
      rvm: 2.6.3
      deploy:
        provider: rubygems
        api_key:
          secure: KcBpkFaes74KGMm8X/rRA8e13+t3PmkefsAvOAR+iF4g1GyuLSPkP92Fb9vFfsXBph+qmFh5rNa2lIRf/3RXW6COxY7CMMaARxUfJOKE0rmIwF0qfKI+RZDh6abg92iYngunMZVN8WVft6Lv9ZTOYCWxr1Zs1Ll/Rl4PfvHNd1g=
        gem: travis
        on:
          repo: travis-ci/travis.rb
          ruby: 2.6.3
